name: Publish Packages

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: GedasFX.SourceGenerators.gRPC.MediatR/GedasFX.SourceGenerators.gRPC.MediatR.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
  
